permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: testing / ${{ matrix.os }} / Java ${{ matrix.java }} / Dist ${{ matrix.dist }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 17, 21 ]
        dist: [ temurin, adopt, oracle ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Setup Java ${{ matrix.java }} / Dist ${{ matrix.dist }}
        with:
          distribution: ${{ matrix.dist }}
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn test